@startuml
'https://plantuml.com/object-diagram

map Signal {
RESET => The game has finished, no response required.
PLAY => The game continues, respond with ClientAction.
}

map HighLowCardsState{
 (int32) cardCount => The total number of cards on the board (face up + face down)
 (repeated) (String) deltCard => The face up cards, examples 'QH', '10C', 'AD'
 (int32) score => The current score
 (enum) signal *-> Signal
}

map HighLowCardAction {
HIGH => The next card is 'higher'
LOW => The next card is 'lower'
}
@enduml
