@startuml
'https://plantuml.com/sequence-diagram

alt Action Request

    Client <-Server: HighLowCardsState signal=PLAY
    Client --> Server: HighLowCardAction

else Reset Notification

    Client <- Server: HighLowCardsState signal=RESET
end

@enduml