@startuml
'https://plantuml.com/object-diagram

map BanditState{
  (int32) banditCount => The number of bandits available.
  (int32) pullCount => The number of pulls available in each game.
  int32 pull => The number of **this** pull.
}

@enduml